name: Format

on:
  push:
    paths-ignore:
      - .github/workflows/**

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run format if needed
        run: npx prettier --check . || npx prettier --write .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: ':green_heart: Auto format'
